#ifndef MAIN_H
#define MAIN_H

/* XINPUT gamepad definitions 
XINPUT_GAMEPAD_DPAD_UP			(1 << 0)
XINPUT_GAMEPAD_DPAD_DOWN		(1 << 1)
XINPUT_GAMEPAD_DPAD_LEFT		(1 << 2)
XINPUT_GAMEPAD_DPAD_RIGHT		(1 << 3)
XINPUT_GAMEPAD_START			(1 << 4)
XINPUT_GAMEPAD_BACK				(1 << 5)
XINPUT_GAMEPAD_LEFT_THUMB		(1 << 6)
XINPUT_GAMEPAD_RIGHT_THUMB		(1 << 7)
XINPUT_GAMEPAD_LEFT_SHOULDER	(1 << 8)
XINPUT_GAMEPAD_RIGHT_SHOULDER	(1 << 9)
XINPUT_GAMEPAD_A				(1 << 10)
XINPUT_GAMEPAD_B				(1 << 11)
XINPUT_GAMEPAD_X				(1 << 12)
XINPUT_GAMEPAD_Y				(1 << 13)
*/

#define MAX_PATH_SIZE 512
#define MAX_LINE_SIZE 256
#define MAX_CONFIG_LEFT_SIZE 64

typedef enum _GAMEPAD_BUTTONS {
	GAMEPAD_NOT_REMAPPED       =0,
	GAMEPAD_DPAD_UP			       =1,
	GAMEPAD_DPAD_DOWN		       =2,
	GAMEPAD_DPAD_LEFT		       =3,
	GAMEPAD_DPAD_RIGHT	       =4,
	GAMEPAD_START			         =5,
	GAMEPAD_BACK			         =6,
	GAMEPAD_L3				         =7,
	GAMEPAD_R3				         =8,
	GAMEPAD_LB				         =9,
	GAMEPAD_RB				         =10,
	GAMEPAD_A				           =11,
	GAMEPAD_B				           =12,
	GAMEPAD_X				           =13,
	GAMEPAD_Y	                 =14,
	GAMEPAD_LSTICK_UP          =15,
	GAMEPAD_LSTICK_DOWN		     =16,
	GAMEPAD_LSTICK_LEFT		     =17,
	GAMEPAD_LSTICK_RIGHT	     =18,
	GAMEPAD_RSTICK_UP          =19,
	GAMEPAD_RSTICK_DOWN		     =20,
	GAMEPAD_RSTICK_LEFT		     =21,
	GAMEPAD_RSTICK_RIGHT	     =22,
	GAMEPAD_LT                 =23,
	GAMEPAD_RT                 =24,
	GAMEPAD_LEFT_TOUCHPAD	     =25,
	GAMEPAD_RIGHT_TOUCHPAD	   =26,
	GAMEPAD_NUMBER_OF_BUTTONS,
  GAMEPAD_DISABLE            =0xFF
} GAMEPAD_BUTTONS;

typedef enum _SHIFT_CONFIG {
	SHIFT_NONE=0,
	SHIFT_LEFT_THUMB,
	SHIFT_RIGHT_THUMB,
	SHIFT_LB_RB_LT_RT,
	SHIFT_COUNT
} SHIFT_CONFIG;

typedef struct _GAMEPAD_BUTTON_MAP {
	GAMEPAD_BUTTONS ButtonMap[GAMEPAD_NUMBER_OF_BUTTONS];
	SHIFT_CONFIG	ShiftConfig;
	GAMEPAD_BUTTONS ShiftButtonMap[GAMEPAD_NUMBER_OF_BUTTONS];
} GAMEPAD_BUTTON_MAP;



#endif
